Repository gardener/test-infra, pull requests merged in 2024-05, with the labels that each got.

#514 chore: Update Concourse URL
  README.md
Labels: area/documentation, kind/cleanup, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#516 Update the path to conformance pr config item
  cmd/cncf-conformance-pr-creator/create_pr_k8s_conformance.py
Labels: kind/bug, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs, area/testing

#517 Convert cfg data to string
  cmd/cncf-conformance-pr-creator/create_pr_k8s_conformance.py
Labels: kind/bug, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs, area/testing

#518 refactor: Clean up imports and re-use cfg-factory
  cmd/cncf-conformance-pr-creator/create_pr_k8s_conformance.py
Labels: kind/cleanup, reviewed/ok-to-test, reviewed/lgtm, size/s, area/compliance

#519 Update go dependencies and argo wf
  .golangci.yaml
  charts/testmachinery/charts/argo/values.yaml
  charts/testmachinery/values.yaml
  go.mod
  go.sum
  pkg/testmachinery/locations/location/gitlocation.go
  pkg/testrunner/result/status-uploader.go
  pkg/tm-bot/github/client.go
  pkg/tm-bot/github/manager.go
  pkg/tm-bot/github/mocks/client.go
  pkg/tm-bot/github/types.go
  pkg/tm-bot/hook/handler.go
  pkg/tm-bot/plugins/test/common/run.go
  pkg/tm-bot/tests/tests_test.go
  pkg/tm-bot/ui/auth/auth.go
  pkg/tm-bot/ui/pages/status.go
  pkg/util/util.go
Labels: kind/task, needs/ok-to-test, reviewed/lgtm, size/l, area/testing
