Repository gardener/test-infra, pull requests merged in 2024-10, with the labels that each got.

#532 Ocm and cleanup
  Dockerfile
Labels: needs/ok-to-test, reviewed/lgtm, size/s

#537 Install ocm-cli release versions
  Dockerfile
Labels: area/delivery, kind/cleanup, needs/ok-to-test, reviewed/lgtm, size/xs

#536 Replace `kubetest` with `hydrophone` framework
  .ci/check
  .ci/integration
  .ci/integration-bot
  .ci/test
  .ci/test-definitions
  .test-defs/conformanceTestgrid.yaml
  .test-defs/conformanceTestgridParallel.yaml
  Makefile
  cmd/cncf-conformance-pr-creator/create_pr_k8s_conformance.py
  conformance-tests/README.md
  conformance-tests/config/config.go
  conformance-tests/hydrophone/hydrophone.go
  conformance-tests/main.go
  conformance-tests/publish/parse_junit.go
  conformance-tests/publish/publish.go
  integration-tests/e2e/README.md
  integration-tests/e2e/config/config.go
  integration-tests/e2e/kubetest/desc_generator.go
  integration-tests/e2e/kubetest/description/1.25/false_positives.json
  integration-tests/e2e/kubetest/description/1.25/skip.json
  integration-tests/e2e/kubetest/description/1.25/test.json
  integration-tests/e2e/kubetest/description/1.25/working.json
  integration-tests/e2e/kubetest/description/1.26/false_positives.json
  integration-tests/e2e/kubetest/description/1.26/skip.json
  integration-tests/e2e/kubetest/description/1.26/test.json
  integration-tests/e2e/kubetest/description/1.26/working.json
  integration-tests/e2e/kubetest/description/1.27/false_positives.json
  integration-tests/e2e/kubetest/description/1.27/skip.json
  integration-tests/e2e/kubetest/description/1.27/test.json
  integration-tests/e2e/kubetest/description/1.27/working.json
  integration-tests/e2e/kubetest/description/1.28/false_positives.json
  integration-tests/e2e/kubetest/description/1.28/skip.json
  integration-tests/e2e/kubetest/description/1.28/test.json
  integration-tests/e2e/kubetest/description/1.28/working.json
  integration-tests/e2e/kubetest/description/1.29/false_positives.json
  integration-tests/e2e/kubetest/description/1.29/skip.json
  integration-tests/e2e/kubetest/description/1.29/test.json
  integration-tests/e2e/kubetest/description/1.29/working.json
  integration-tests/e2e/kubetest/description/1.30/false_positives.json
  integration-tests/e2e/kubetest/description/1.30/skip.json
  integration-tests/e2e/kubetest/description/1.30/test.json
  integration-tests/e2e/kubetest/description/1.30/working.json
  integration-tests/e2e/kubetest/description/1.31/false_positives.json
  integration-tests/e2e/kubetest/description/1.31/skip.json
  integration-tests/e2e/kubetest/description/1.31/test.json
  integration-tests/e2e/kubetest/description/1.31/working.json
  integration-tests/e2e/kubetest/kubetest_runner.go
  integration-tests/e2e/kubetest/publisher.go
  integration-tests/e2e/kubetest/results_evaluator.go
  integration-tests/e2e/kubetest/setup/setup.go
  integration-tests/e2e/kubetest/xml_junit_result.go
  integration-tests/e2e/main.go
  integration-tests/e2e/util/dump/dump.go
  integration-tests/e2e/util/sets/string.go
  integration-tests/e2e/util/util.go
Labels: kind/technical-debt, needs/ok-to-test, needs/second-opinion, size/xl, area/testing
