Repository gardener/test-infra, pull requests merged in 2025-04, with the labels that each got.

#647 bump hydrophone version for conformance tests
  .test-defs/conformanceTestgrid.yaml
  .test-defs/conformanceTestgridParallel.yaml
Labels: kind/task, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs, area/testing

#650 fix: Pass github_api to GitHubRepositoryHelper
  .ci/it-prepare.py
  cmd/cncf-conformance-pr-creator/create_pr_k8s_conformance.py
Labels: kind/bug, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs, area/testing

#651 fix: Initialize repo_url in github_cfg
  cmd/cncf-conformance-pr-creator/README.md
  cmd/cncf-conformance-pr-creator/create_pr_k8s_conformance.py
Labels: kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs, area/testing

#663 Add `yq` to base image
  Dockerfile
Labels: area/dev-productivity, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#664 Add team label to component descriptor
  .ci/pipeline_definitions
Labels: kind/task, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs, area/testing
